# Generated by Django 2.2.4 on 2022-01-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skateboardparks',
            table='skateboard_parkdata',
        ),
    ]
